# Generated by Django 5.0.6 on 2024-05-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('emails', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=80)),
                ('subcity', models.CharField(max_length=80)),
                ('phonenum', models.IntegerField()),
            ],
        ),
    ]
