# Generated by Django 5.0.6 on 2024-05-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cateringAPP', '0002_apointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('packimg', models.ImageField(upload_to='')),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
