# Generated by Django 5.0.6 on 2024-06-27 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cateringAPP', '0003_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField(blank=True, null=True)),
                ('menu_categories_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='cateringAPP.package')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='menu_items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='cateringAPP.menucategory')),
                ('packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitemspack', to='cateringAPP.package')),
            ],
        ),
    ]
